/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Sat Jan 21 2017 16:51:18 GMT-0800 (PST)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
"use strict";
exports.ENV = {};

//# sourceMappingURL=env.js.map
